### PR TITLE
final

### PR DESCRIPTION
**Pull request by SteadyAction**

### CODE REVIEW

**Comment by an-ju** [comment]
Did you remove cucumber tests?  Can you explain the reasons?  Are your rspec tests enough to cover the features?

**Comment by an-ju** [comment]
BTW, there is no need to create a new PR.  Your new commits on the master branch will automatically appear here.

**Comment by an-ju** [comment]
@SteadyAction Any updates on my latest comments?

**Comment by SteadyAction** [comment]
Oh. We mistakenly worked on a wrong repo. I will pull the works to my forked repo so this pull requests will be updated soon! (in 2 hours) Sorry 😐.

**Comment by Matt-Lambster** [comment]
We found that we were most comfortable with using rspec to test our features. Most of the code that we needed to test was back end things, which we found rspec to be more suited for (as a lot of the results that we were looking for weren't obvious or visible to the user so capybara wouldn't be too useful). Hope that clarifies why we only used rspec.

**Pull request merged**
